### ISSUE TITLE
US 1 - List of Camping Trip Cards

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#1]
## Value proposition

As a user
I want to have a list of Campingtrips
so that I can overview about my Campingtrips

## Description

![Image](https://user-images.githubusercontent.com/132760864/251382967-dc875e59-502d-4ac1-a0c5-f58835363bd5.png)

## Acceptance criteria

- [ ] A Headline "Organize your Camping Trips" is Displayed
- [ ] Camping Trips are displayed as cards in a list
- [ ] The card include the Location, the date and the friends

## Tasks

- [ ] Create a feature Branch
- [ ]  Create campingtrips mock array
- [ ]  Create a headline for the list
- [ ]  Create component `CardSummary`
- [ ]  Create component `CardList` with Trips
- [ ]  Map the list of trips
