### ISSUE TITLE
US 6 - Direct to ListPage

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#10]
US 7

## Value proposition

As an user

I want to get directed to the listpage after click the add button

So that i am able to see immediately the new trip.

## Description

![Image](https://user-images.githubusercontent.com/132760864/253568420-711627d2-8439-4743-b636-36e60e0dc523.png)

## Acceptance criteria

- [ ] after clicking to add trip button you get directed to listpage

## Tasks

- [ ] create a new feature branch `feature/DirectListPage
- [ ] add a link to the button
