### ISSUE TITLE
US 8-Bug fixing

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#13]
US 8

## Value proposition

As an user

I want to get directed to the list page after i saved the edited trip

So that i am able to see immediately the edited trip in my list.

## Description

![Image](https://user-images.githubusercontent.com/132760864/254841127-285afd0e-c127-425b-89ea-9fc49895ed3c.png)

## Acceptance criteria

- [ ] after clicking Save changes you'll get directed to list page

## Tasks

- [ ] create a new feature branch `feature/SaveChanges
- [ ] fixing the Bug (TypeError: onAddTrip is not a function)
- [ ] implement routing to the list component on the save change button

**Comment by Roland-Hufnagel** [comment]
Hi. I do not see any tasks that implement the routing to the list page. Please add a task as it is the main value of this userstory.

**Comment by Roland-Hufnagel** [comment]
I think you ment 'list'-comonent, not 'link'-component 😀
