### ISSUE TITLE
US 9 - Add Cloudenary

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#14]
US 9

## Value proposition

As an user

I want to upload a Image to the trip

So that i am able to see a picture on the detail page.

## Description

![Image](https://github.com/SelcoD/CampingFriends/assets/132760864/27a2a11c-00b8-42f7-bc87-9892870518ea)

## Acceptance criteria

- [ ] after clicking select file, finder pops of where you can select a file
- [ ] after you select a file, the file name is displayed beside upload image
- [ ] by clicking upload , the image uploads in the local storage to the trip

## Tasks

- [ ] create a new feature branch `feature/AddImage
- [ ] Add cloudenary upstream 
- [ ] Implement the image to detail page

**Comment by HannesOster** [comment]
Hey :)

The tasks could be more detailed, but i dont have any recommentions how to do, because i dont know cloudenary yet. Also
you could for example mention  which buttons you´ll add to the page 

The rest looks good to me.

**Comment by VolkerJacobsen** [comment]
Hey Selco, well done! After you implemented the changes Hannes suggested it is much clearer what the US includes.
