### ISSUE TITLE
US 10 - Styling Index

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#16]
US 10

## Value proposition

As an user

I want to have a better user experience

So that I have a nice flow through the app 

## Description

![Image](https://user-images.githubusercontent.com/132760864/256482347-43f37603-3c2f-40f2-88f6-63d2af2fa80c.png)

## Acceptance criteria

- [ ] Icons are displayed under the Trip
- [ ] new trip is displayed in center under the trip

## Tasks

- [ ] create a new feature branch `feature/StyleIndex
- [ ] Add icons to the buttons
- [ ] Style "new trip" like a button
