### ISSUE TITLE
US 11 - Styling Form

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#17]
US 11

## Value proposition

As an user

I want to have a better user experience

So that I have a nice flow through the form 

## Description

![Image](https://user-images.githubusercontent.com/132760864/256500010-0ddeefb8-36f3-402a-8e73-2f8f58cce8b9.png)

## Acceptance criteria

 - [ ] back to list is displayed in center under the form

## Tasks

- [ ] create a new feature branch `feature/StyleForm
- [ ] Add + icon to the ADD button
- [ ] Style "Back to list" like a button
