### ISSUE TITLE
US 12 - Styling Edit

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#18]
US 12

## Value proposition

As an user

I want to have a better user experience

So that I have a nice flow through the Editform 

## Description

![Image](https://user-images.githubusercontent.com/132760864/256502728-b57a3b32-5eee-4744-9c96-b6cee27f4970.png)

## Acceptance criteria

 - [ ] back to list is displayed in center under the form
 - [ ] delete icon is displayed beside the added friends

## Tasks

- [ ] create a new feature branch `feature/StyleEdit
- [ ] Add bin icon to the delete button
- [ ] Style "Back to list" like a button
