### ISSUE TITLE
US 2 - CampingCardDetail Page

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#2]
## Value proposition

As a user
I want to see the Card more detailed
so that I can see more details of the trip

##Description

![Image](https://user-images.githubusercontent.com/132760864/251428493-56cdcef2-dcf0-40c8-afff-bff6db411a32.png)

##Acceptance criteria

- [ ] A Headline `Check the details of your trip` is Displayed
- [ ] The Details are displayed as a card
- [ ] The card include the Location, the exact date with day,
 two small images beside, weather conditions and the the friends

##Tasks

- [ ] Create a feature Branch `feature/DetailPage
- [ ] Add day and weather conditions to mock array
- [ ] Create a headline for the page
- [ ] Create component `CampingCardDetail`
- [ ] Make the `Cards` from the `CardList` clickable to get to the `DetailPage`
- [ ] Create a `Button` to get back to the `CardListPage`
