### ISSUE TITLE
US 3 - Form Page

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#3]
US 3

## Value proposition

As an user
I want to create a trip
So that i am able to add a trip to the list

## Description

![Image](https://github.com/SelcoD/CampingFriends/assets/132760864/3175ec9f-37ee-480c-bd11-0b1d85b13d74)

## Acceptance criteria

- [ ] a Headline with `Add a new trip to your list` is displayed
- [ ] a Form is displayed
- [ ] The form has checkboxes to tick which conditions are expected (windy, 
        cold,hot, large spaces)
- [ ] The form has a field to type in the date
- [ ] The form has a field to add friends
- [ ] the From with the checkboxes should be displayed
- [ ] i am able to fill the form
- [ ] the friends form and the checkboxes has not to be filled
- [ ] if the user forgot to fill the Location or the date form, a infobox appear next to the form.
- [ ] the Location, the date has to be filled
- [ ] the page should be scrollable

## Tasks

- [ ] create a new feature branch `feature/FormPage
- [ ] create a new Headline for the page
- [ ] create a component `CampingTripForm`
- [ ] create a `Button` on the `ListPage` wich navigates to `FormPage`

**Comment by tejue** [comment]
Hey Selco, looks good. Just some small adjustments...oh I know the pain of a form :)

Value Proposition: 
You could be just a little bit more precise. Maybe like this:

As a user
I want to create my trip
So that i can add this trip to my list OR So I know where I planed to travel on which date

Acceptance Criteria:
As a developer I wouldn't know exactly what to do with the form. Be as precise as possible, like:
- A form is displayed
- The form has a field to type in the location
- The form has checkboxes to tick which conditions are expected (windy, cold, hot, large spaces)
- The form has a field to type in the date
- The form has a field to add friends
...

Also, what happens, if the location and date are not filled out. Is there an alert appearing?

Oh and two more things: right now your user wants to add this trip to his*her list of trips but the button to do so is missing. As the list already exists I think you can add this button to your acceptance criteria. And you might want to tell the developer, that all of this is on a new page (not sure about this one but you say so in your tasks which your developer doesn't know)

**Comment by SelcoD** [comment]
Hi, thank you for the review.
In this US3 i create a button to get from the ListPage to the FormPage, the button to add this Form to the ListPage will be the step in US 4.

**Comment by RonnySteady** [comment]
Looks good to me, the ideas from tejue are well implemented.

**Comment by SelcoD** [comment]
Thank you
