### ISSUE TITLE
US 4 - Add Buttons to Form Page

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#4]
US 4

## Value proposition

As an user

I want to create a trip with a form

So that i am able to add a trip to the list

## Description

![Image](https://github.com/SelcoD/CampingFriends/assets/132760864/7f9372c2-a67e-486f-a27a-1aa0205f2999)

## Acceptance criteria

- [ ] a `Delete` button is displayed beside the friends form

- [ ] a  `Add this trip` button is displayed in the footer

## Tasks

- [ ] create a new feature branch `feature/FormButtons
- [ ] create a new `Button` wich add the new trip to the `CardListPage`
- [ ] create a new `Button` wich deletes the added friend

**Comment by JivanaLipsewers** [comment]
lgtm! :)

**Comment by SelcoD** [comment]
thank you!
