### ISSUE TITLE
US 5 - Connect Form with Data

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#8]
US 5

## Value proposition

As an user

I want to click add this trip

So that i am able to see the new trip on Listpage

## Description

![Image](https://user-images.githubusercontent.com/132760864/253541164-1687fe86-c28f-4381-9e07-291e1d177858.png)

## Acceptance criteria

- [ ] the new created trip displayed in the Listpage

## Tasks

- [ ] create a new feature branch `feature/AddToList
- [ ] connect the form inputs with the campingTrips data

**Comment by ArnelaKapllani** [comment]
LGTM 👍
