### ISSUE TITLE
US 7- Delete/Edit function and Detailcard for new Trip

### ISSUE THREAD

**Issue by SelcoD** [SelcoD/CampingFriends#9]
US 6

## Value proposition

As an user

I want to edit and delete a trip from listpage

So that i am able to organize the listpage better.

## Description

![Image](https://user-images.githubusercontent.com/132760864/253542230-9f929850-982c-471f-892f-5f71881ad5f7.png)

## Acceptance criteria

- [ ] a edit button should be displayed beside the new trip card
- [ ] a delete button should be displayed beside the new trip card
- [ ] by clicking the delete button, the card should be deleted
- [ ] by clicking the edit button, you get directed to the formPage
- [ ] by clicking on one of the new Trips, you be able to see a Detailcard

## Tasks

- [ ] create a new feature branch `feature/EditTrip
- [ ] create a new `Button` wich edit the trip on the `ListPage`
- [ ] create a new `Button` wich deletes the  trip

**Comment by ArnelaKapllani** [comment]
Hi Selco 😊 maybe you have to modify a little bit the Value proposition and Acceptance criteria.
Respectivly: 

Value proposition 
As a user
I want to edit and delete a trip from the list page
So that I can organize the list page better

Acceptance criteria
The new TripCard should be displayed.
A delete button beside the TripCard should be displayed.
An edit button beside the TripCard should be displayed.

**Comment by SelcoD** [comment]
Hi Arnela, the new trip gets Displayed at US 5.
